name: CI/CD Databricks Asset Bundle

on:
  push:
    paths:
      - 'data_forge_asset/**'
      - '.github/workflows/databricks-ci-cd.yml'
    branches: [main]

jobs:
  build-test-upload:
    name: Databricks Asset Bundle
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install databricks

      - name: Validar Databricks Bundle
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          databricks bundle validate --target prod --profile prod

      - name: Deploy Databricks Bundle
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          databricks bundle deploy --target prod --profile prod
